var emblemsNotInPacks_withDescriptions = {
	"Builder":"Spartan Rank 5",
	"Elementary":"Spartan Rank 2",
	"Knot":"Spartan Rank 3",
	"Links":"Spartan Rank 4",
	"Avian":"Spartan Rank 30",
	"Celestial":"Spartan Rank 35",
	"Cone'd":"SPNKR Pack",
	"Ground Pound":"Geronimo Pack",
	"Killer Bee":"Spartan Rank 15",
	"Navy":"Spartan Rank 50",
	"ODST":"Spartan Rank 40",
	"Patch":"Spartan Rank 25",
	"Principle":"Spartan Rank 10",
	"Stealth":"Spartan Rank 20",
	"All Square":"Suppressor Pack",
	"Anchorite":"And Stay Off Pack",
	"Angels' Mark":"Banshee Destroyer Pack",
	"Antelope":"Flag Victory Pack",
	"AR Start":"Assault Rifle Pack",
	"Army":"Spartan Rank 60",
	"Arrow on Target":"Binary Rifle Pack",
	"Assassin":"Assassin Pack",
	"Axiom":"Storm Rifle Pack",
	"Blue Team":"Spartan Rank 90",
	"Bolt":"Boltshot Pack",
	"Bulltrue":"Combat Opportunist Pack",
	"Campfire":"Head in the Game Pack",
	"CAMS":"Scorpion Destroyer Pack",
	"Cascade Stronghold Technologies":"Wraith Destroyer Pack",
	"Chief's Crest":"Weapon Mastery Pack",
	"Confirmation":"Sniper Rifle Pack",
	"Covenant Signet":"Covenant Destroyer Pack",
	"Crash":"Splatter Pack",
	"Cubicle":"Warthog Destroyer Pack",
	"Eco":"Stronghold Victory Pack",
	"Enlisted":"Hydra Launcher Pack",
	"Equilateral":"Gausshog Gunner Pack",
	"Eye of the Beast":"Whites of Their Eyes Pack",
	"Falcon":"Shotgun Pack",
	"Fireborn":"Railgun Pack",
	"Fireteam Crimson":"Jackal Slayer Pack",
	"Fireteam Osiris":"Spartan Rank 80",
	"Flaming Skull":"Spartan Spree Pack",
	"Flip Mode":"",
	"Forerunner Signet":"Forerunner Destroyer Pack",
	"Frontier":"Aggressive Expansion Pack",
	"Great Hunt":"Big Game Hunter Pack",
	"Hand of the Didact":"Warden Slayer Pack",
	"Hannibal Weapon Systems":"Wonderful Toys Pack",
	"Hastati":"Wargoose Gunner Pack",
	"Headshot":"Bullet in the Brain Pack",
	"Hunter Prey":"Hunter Slayer Pack",
	"Imperial":"Storm the Walls Pack",
	"Implied":"Magnum Pack",
	"Incinerate":"Incineration Cannon Pack",
	"Invex":"Scattershot Pack",
	"Jewel":"Knight Slayer Pack",
	"Listener":"Beam Rifle Pack",
	"Loading":"Banshee Gunner Pack",
	"Loupe":"Mine! Pack",
	"Mantis":"Mantis Destroyer Pack",
	"Marauder":"Marine Replicant Slayer Pack",
	"Mark of the Hog":"Warthog Gunner Pack",
	"Matrix":"Crawler Slayer Pack",
	"Maw":"Elite Slayer Pack",
	"Meteor":"Phaeton Gunship Gunner Pack",
	"Mixer":"SAW Pack",
	"Mushroom":"Rocket Launcher Pack",
	"Naded":"Frag Grenade Pack",
	"Network":"Watcher Slayer Pack",
	"Nexus":"Light Rifle Pack",
	"Noble":"Defender of the Flag Pack",
	"Noise":"Spartan Rank 130",
	"Nucleus":"Rockethog Gunner Pack",
	"ONI":"Spartan Rank 70",
	"Options":"Assistant Pack",
	"Orbit":"Conqueror Pack",
	"Panda BR":"Battle Rifle Pack",
	"Pinwheel":"Carbine Pack",
	"Pioneer":"Phaeton Gunship Destroyer Pack",
	"Pirate":"Ghost Destroyer Pack",
	"Pivot":"Spartan Laser Pack",
	"Platform":"Flag Mastery Pack",
	"Prancer":"Plasma Grenade Pack",
	"Predator":"Hunter Pack",
	"Prime":"Carrier Takedown Pack",
	"Radioactive":"Fuel Rod Cannon Pack",
	"Ratio":"Spartan Rank 100",
	"Reclaimer":"Soldier Slayer Pack",
	"Revolve":"Wheelman Pack",
	"Rhino":"Juggernaut Pack",
	"Salient Sword":"Energy Sword Pack",
	"Scarab":"Needler Pack",
	"Scorpion":"Scorpion Gunner Pack",
	"Screw":"Mongoose Destroyer Pack",
	"Signal":"Spartan Rank 115",
	"Spartan League":"Breakout Victory Pack",
	"Spartan Seal":"Bulldozer Pack",
	"Splinter":"Splinter Grenade Pack",
	"Tag It":"DMR Pack",
	"Teeth":"Grunt Slayer Pack",
	"Three Eyes":"Multikill Pack",
	"Traitor":"Spartan Slayer Pack",
	"Triad":"Smash Pack",
	"Triarch":"Protector Pack",
	"Unicorn":"Mantis Gunner Pack",
	"UNSC":"Slayer Victory Pack",
	"Volatile":"Plasma Caster Pack",
	"Warlord":"Against All Odds Pack",
	"Wasp":"Ghost Gunner Pack",
	"Watershed Division":"Close Quarters Pack",
	"Waves":"Wraith Gunner Pack",
	"Winged":"Unstoppable Pack",
	"Apollo":"Unknown; likely Legendary LootCrate",
	"Awake":"Spartan Rank 148",
	"Cognate":"Spartan Rank 146",
	"Confine":"Loadout Weapon Mastery Pack",
	"Counter Logic Gaming":"HCS Counter Logic Gaming (CLG) Pack",
	"Evil Geniuses":"HCS Evil Geniuses (EG) Pack",
	"Grenadier":"Grenade Mastery Pack",
	"Halo World Championship 2016":"Available through Halo World Championship Pack",
	"Iris":"Slayer Mastery Pack",
	"Isosceles":"Forerunner Power Weapon Mastery Pack",
	"January 2016 Season":"Qualify during January 2016 Season",
	"Kindred":"Spartan Rank 145",
	"OpTic Gaming":"HCS Optic Gaming (OG) Pack",
	"Pyramid":"Breakout Mastery Pack",
	"Slumber":"Spartan Rank 147",
	"Spartan-IV":"UNSC Power Weapon Mastery Pack",
	"Summit":"Stronghold Mastery Pack",
	"Thanks Given":"Thanksgiving REQ Pack",
	"Unworthy":"Covenant Power Weapon Mastery Pack",
	"Beta Prime":"Halo 5 Beta",
	"Beta Recruit":"Halo 5 Beta",
	"Beta Star":"Halo 5 Beta",
	"Candy Canes":"Christmastime REQ Pack",
	"February 2016 Season":"Qualify during February 2016 Season",
	"Great Wheel":"Vehicle Mastery Pack",
	"Guardian":"Spartan Rank 151",
	"Halo Championship Series":"HCS Pack",
	"Halo Channel":"Halo Channel Promo Pack",
	"Librarian":"Halo Community Feedback Program",
	"Magnum Opus":"Arena Mastery Pack",
	"Mantle":"Spartan Rank 152",
	"March 2016 Season":"Qualify during March 2016 Season",
	"May 2016 Season":"Qualify during May 2016 Season",
	"Season 4":"Qualify during April 2016 Season",
	"Sentient":"Spartan Rank 149",
	"Spartan Claus":"Christmastime REQ Pack",
	"True Light":"Spartans Will Never Walk Alone pack",
	"Warden":"Spartan Rank 150",
	"War's Quintet":"Warzone Mastery Pack"
};
